### PR TITLE
Add example of disabling ssl cert check

### LINKED ISSUE #112: Add example of disabling SSL/TLS cert checking
From https://github.com/rusoto/rusoto/issues/1277 :

> Hello! I'm using rusoto to build an internal tool for testing, we use localstack with SSL enabled. With other tools, we can disable the cert check with an environment variable but I couldn't find anything similar here.  How can I disable the cert check? Thanks :)

We can [do this](https://github.com/rusoto/rusoto/issues/1277#issuecomment-459598507) but it's not straightforward. Let's add docs to make it easier to follow!

### PR DESCRIPTION
**Pull request by itsHabib**
Fixes #112

### CODE REVIEW

**Comment by matthewkmayer** [comment]
Thank you!

The new page looks good and addresses our needs. 🎉 

Did you get a chance to test it out with a self-signed cert? 😄

**Comment by itsHabib** [comment]
> Thank you!
> 
> The new page looks good and addresses our needs. tada
> 
> Did you get a chance to test it out with a self-signed cert? smile

Good question @matthewkmayer . I have not, let me do that. Do you think adding that to the example would be helpful? The creation of the certificate and adding of the certificate to the builder?

**Comment by matthewkmayer** [comment]
I think the intended audience will already have self-signed certs set up. My request is a verification it works as expected. 😄 

We don't need any code or documentation added to the repository, but a verification on your system that it works would be awesome. 👍

**Comment by itsHabib** [comment]
> I think the intended audience will already have self-signed certs set up. My request is a verification it works as expected. 😄
> 
> We don't need any code or documentation added to the repository, but a verification on your system that it works would be awesome. 👍

Sounds good. I should be able to do that tonight.

**Comment by itsHabib** [comment]
Hey @matthewkmayer , not sure if the implementation is wrong or if I am not creating my cert correctly, but am getting an error with:
```
thread 'main' panicked at 'failed to list buckets: HttpDispatch(HttpDispatchError { message: "error trying to connect: invalid URL, scheme must be http" })', src/libcore/result.rs:999:5
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
I used https://github.com/FiloSottile/mkcert to create the cert. Do you have any recommendations here?

**Comment by matthewkmayer** [comment]
I'd try using another AWS SDK to see if it's in this implementation or if it's an issue with the cert. 😄

**Comment by itsHabib** [comment]
> I'd try using another AWS SDK to see if it's in this implementation or if it's an issue with the cert. smile

I figured it out by looking at the constructor of the `HttpsConnector`. The important part I left out is that you have to make sure the http connector isn't enforcing http.

**Comment by matthewkmayer** [comment]
Great, thank you!

**Pull request merged**
